config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :poems, only: [:index, :show]
  get '/add-poem-as-admin', to: 'poems#new'
  post '/add-poem-as-admin', to: 'poems#create'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poem.rb
class Poem < ApplicationRecord

  mount_uploader :photo, PhotoUploader

  MONTHS     = [nil, 'January', 'February', 'March', 'April',
                'May', 'June', 'July', 'August', 'September',
                'October', 'November', 'December']

  DAYS       = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday',
                'Friday', 'Saturday']

  def humanize_date
    "#{MONTHS[created_at.month]} #{created_at.day}, #{created_at.year}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController

  def index
    @poems = Poem.all
  end

  def new
    @poem = Poem.new
  end

  def create
    poem_params = params.require(:poem).permit(:title, :body, :category, :photo) 
    poem = Poem.new(poem_params)

    if poem.save
      redirect_to poem_path(poem)
    else
      render :new
    end
  end

  def show
    @poem = Poem.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Jenny Erlanger | Australian Children's Poet</title>
    <meta property="og:image" content="https://res.cloudinary.com/dkft9hkkv/image/upload/v1547913148/Erlanger%20Poetry/facebook_image.jpg">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('favicon.png'), rel: 'icon', type: 'image/png' %>
  </head>
  <body>
    <div id="bootstrap-overrides">

      <% if current_page?('/') %>
        <%= render 'shared/navbar-home' %>
      <% else %>
        <%= render 'shared/navbar' %>
      <% end %>

      <div class="ensure-height">
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="add-space"></div>
<div class="poem-container">

  <!-- TEXT SIDE -->
  <div class="about-text">
    <h2>ABOUT ME</h2>
    <p><strong class="date">My journey through poetry.</strong></p>
    <br>

    <div class="body-and-image">

      <div class="text-half">
        <p>Having retired from the teaching profession after thirty years of instructing middle school students in French, Mathematics and English, I've now found extra time to devote to my life-long passion of poetry writing.</p>

        <p>Since early childhood when I was introduced to A.A Milne’ poetry, I have always been drawn to rhyming and rhythmic verse – and I still gravitate towards this genre in my own writing. A prolific poet during my primary school years, I have continued to find poetry an excellent medium for recording the observations, particular moments and feelings experienced in the course of our everyday lives.</p>

        <p class="final-paragraph">Although I have written poems on a diverse range of themes, the bulk of my creative energy finds an outlet in the hundreds of poems I have written through the eyes of a child.  Given that childhood is such a short and precious phase in the human life cycle, I feel drawn to immortalising the ups and downs of being a child in a way that can be easily and fondly remembered.</p>
      </div>

      <div class="image-half about-header" style="background-image: url('https://res.cloudinary.com/dkft9hkkv/image/upload/v1545510748/Erlanger%20Poetry/Kiss.jpg');">
      </div>


    </div>

    <br>
    <div class="about-footer">
      <%= link_to "My poems →", poems_path, class: 'backlink'  %>
      <p class="photography"><em><strong>Photography: </strong>
      All photos on this website come courtesy of my darling husband, Peter Erlanger.</em></p>
    </div>

  </div>

</div>

<div class="add-space"></div>

app/views/pages/contact.html.erb
<div class="add-space"></div>
<div class="contact-container">

  <!-- TEXT SIDE -->
  <div class="contact-text-main">
    <h2>CONTACT</h2>
    <p><strong class="date">Get in touch.</strong></p>
    <br>


    <div class="text-and-form">

      <!-- BODY TEXT -->
      <div class="contact-text">
        <p>If you’d like to collaborate on a project, commission a poem, or just chat about your experiences, I’d love to hear from you.</p>
        <p class="final-paragraph">Feel free to reach out via the contact form on this page, or send me an email directly:
        <br><br><a href="mailto:jennyerlanger@optusnet.com.au" target="_blank">jennyerlanger@optusnet.com.au</a></p>
      </div>

      <!-- FORM -->
      <div class="form-flex">
        <div class="contact-form">
          <form id="full-form" action="https://formspree.io/a.erlanger@gmail.com" target="_blank" method="post" enctype="text/plain">

          <div class="name-and-email">

            <div class="form-name">
              <span class="form-label">Name</span><br>
              <input class="default-form right-margin" type="text" name="name">
            </div>

            <div class="form-email">
              <span class="form-label">Email</span><br>
              <input class="default-form" type="email" name="_replyto" required>
            </div>

          </div>

          <span class="form-label">Message</span><br>
          <textarea id="comment-field" name="message" class="default-form" rows="3" required></textarea>
          <input id="submit-button" class="form-button" type="submit" value="Send">
          </form>
        </div>
      </div>

  </div>

</div>

<div class="add-space"></div>

<script>
  let submitButton = document.getElementById("submit-button");
  let fullForm = document.getElementById("full-form");
  submitButton.onmouseup = resetForm;

  function resetForm(e) {
    alert("Thank you, I'll get back to you as soon as I can :)");
    fullForm.reset();
  }
</script>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url('https://res.cloudinary.com/dkft9hkkv/image/upload/v1547061876/Erlanger%20Poetry/homepage-cover.jpg');">
  <div class="banner-content">
    <h1>Jenny Erlanger</h1>
    <p class="tagline">Australian Children's Poet</p>
  </div>
</div>


<div class="homepage-heading text-center">
  <h2>"Listen to the voice that speaks inside."</h2>
  <p><strong class="quote-author">– Shel Silverstein</strong></p>
</div>

  <div class="homepage-content">
    <div class="homepage-image" style="background-image: url('https://res.cloudinary.com/dkft9hkkv/image/upload/v1547062154/Erlanger%20Poetry/homepage-avatar.jpg');">
    </div>
    <div class="homepage-text">
      <p><strong>I've been writing poetry for as long as I can remember.</strong></p>
      <div class="text-main">
        <p>And I still have a lot of the poems I wrote from when I was a young child, like the one about my parents picking up my baby brother from the ‘baby shop’.</p>

        <p>A lot has changed since the 1950s, (I know where babies come from now, for one) but my love of poetry has never faltered.</p>

        <p>After thirty-odd years as a secondary school teacher, I retired to pursue the dreams of my inner child - whose voice, simply put, just never shut up.</p>
      </div>
  </div>
</div>


<div class="banner featured" style="background-image: linear-gradient(-225deg, rgba(60,60,60,0.9) 0%, rgba(30,30,30,0.6) 50%), url('https://res.cloudinary.com/dkft9hkkv/image/upload/v1547062261/Erlanger%20Poetry/as-featured-in.jpg');">
  <div class="featured-content">
    <p class="author-quote">“I’ve found poetry a fantastic outlet for expressing my awe of certain aspects of nature and exploring what I see as the messages the natural world has for us regarding different aspects of our everyday lives as human beings.”</p>
    <!-- <h2>AS FEATURED IN:</h2>
    <div class="flexbox-horizontal">
      <span class="featured-brand"><strong style="color: white;">GIGGLES<br>& NIGGLES</strong></span>
      <span class="featured-brand"><strong style="color: white;">AUSTRALIAN<br> CHILDREN'S POETRY</strong></span>
      <span class="featured-brand"><strong style="color: white;">TOOLANGI<br> POETRY SOCITEY</strong></span>
    </div> -->
  </div>
</div>

app/views/poems/index.html.erb
<div class="container">
  <div class="index-heading">
    <p><strong>Published works.</strong></p>
    <p>A small sample of my poems from various publications.</p>
  </div>

  <div class="row">
    <% @poems.each do |poem| %>

    <% photo_string = "https://picsum.photos/#{rand(600..800)}/#{rand(600..800)}" %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= poem.photo %>);">
        <div class="card-category"><%= poem.category %></div>
        <div class="card-description">
          <h2><%= poem.title %></h2>
        </div>
        <%= link_to "", poem_path(poem), class: "card-link" %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="add-space"></div>
</div>

app/views/poems/new.html.erb
<div class="add-space"></div>

<div class="poem-container">

  <div>
    <h2>Add a New Poem</h2>
  </div>

  <%= simple_form_for @poem, url: '/add-poem-as-admin' do |f| %>
    <%= f.input :title %>
    <%= f.input :body, as: :text, input_html: { rows: 10 } %>
    <%= f.input :category %>
    <%= f.input :photo, label: "Puggo Illustration" %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.button :submit %>
  <% end %>

</div>

app/views/poems/show.html.erb
<% photo_string = "https://picsum.photos/#{rand(600..800)}/#{rand(600..800)}" %>
<div class="add-space"></div>
<div class="poem-container">

  <!-- IMAGE -->
  <div class="poem-header" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.3) 0%, rgba(0,36,61,0.3) 50%), url(<%= photo_string %>);">
  </div>

  <!-- TEXT -->
  <div class="poem-text">
    <h2><%= @poem.title %></h2>
    <p><strong class="date"><%= @poem.humanize_date %></strong></p>
    <br>
    <% lines = @poem.body.split("\n") %>
    <% lines.each do |line| %>
      <p><%= line %></p>
    <% end %>
    <br>
    <%= link_to "Back to all poems →", poems_path, class: 'backlink'  %>
  </div>

</div>

<div class="add-space"></div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to "POEMS", poems_path %>
        <%= link_to "ABOUT", about_path %>
        <%= link_to "CONTACT", contact_path %>
  </div>
  <div class="footer-copyright">
    &copy; Jenny Erlanger Inc. All copyright infrigements are punishable by death.
  </div>
</div>

app/views/shared/_navbar-home.html.erb
<div class="navbar-wagon-home">
  <!-- Logo -->
  <a href="/" id="logo">
    <h3>Jenny<strong>Erlanger</strong></h3>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs">

    <%= link_to "POEMS", poems_path, class: "navbar-wagon-item" %>
    <%= link_to "ABOUT", about_path, class: "navbar-wagon-item" %>
    <%= link_to "CONTACT", contact_path, class: "navbar-wagon-item" %>

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "POEMS", poems_path, class: "navbar-wagon-item" %></li>
        <li><%= link_to "ABOUT", about_path, class: "navbar-wagon-item" %></li>
        <li><%= link_to "CONTACT", contact_path, class: "navbar-wagon-item" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" id="logo">
    <h3>Jenny<strong>Erlanger</strong></h3>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs">

    <%= link_to "POEMS", poems_path, class: "navbar-wagon-item" %>
    <%= link_to "ABOUT", about_path, class: "navbar-wagon-item" %>
    <%= link_to "CONTACT", contact_path, class: "navbar-wagon-item" %>

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "POEMS", poems_path, class: "navbar-wagon-item" %></li>
        <li><%= link_to "ABOUT", about_path, class: "navbar-wagon-item" %></li>
        <li><%= link_to "CONTACT", contact_path, class: "navbar-wagon-item" %></li>
      </ul>
    </div>
  </div>
</div>